# -*- coding: utf-8 -*-
"""F_GRPA01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kY0DxJOzauHEM1rJZauIh9nBkHjghrUF

# Group A
## Assignment 1

### Data Wrangling I

Perform the following operations using Python on any open source dataset (e.g., data.csv) 
1. Import all the required Python Libraries. 
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL of the web site). 
3. Load the Dataset into pandas dataframe. 
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe() function to get some initial statistics. Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame. 
5. Data Formatting and Data Normalization: Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set. If variables are not in the correct data type, apply proper type conversions. 
6. Turn categorical variables into quantitative variables in Python.

### Import all the required Python Libraries.
"""

import pandas as pd
import numpy as np

"""### Load the Dataset into pandas dataframe. """

df = pd.read_csv('/content/titanic.csv')

df.head()

df.tail()

df.sample()

df.iloc[49]

type(df.head())

type(df.iloc[49])

df['Pclass'].head()

df['Pclass'].tail()

df['Pclass'].sample()



df['Pclass'].iloc[5]

df['Pclass'].iloc[0:5]

df[['Pclass']]

df.iloc[5:15:5]

df.iloc[[5,7,30,50]]

"""## Data Preprocessing

#### check for missing values in the data using pandas isnull()
"""

df.isnull()

df.isnull().sum()

df.isna().sum()

df.Cabin.isnull().sum()

df.Cabin.notnull().sum()

"""#### describe() function to get some initial statistics. Provide variable descriptions."""

df.Age.describe()

df.Age.count()

df.Age.min()

df.Age.max()

df.Age.quantile(0.25)

np.round(df.Age.quantile(0.25),2)

df.info()

df.index

df.columns

df.dtypes

df.memory_usage()

df['Age'].dtypes



"""#### Types of variables"""

# code here

"""#### Check the dimensions of the data frame"""

df.shape

df.shape[0]

df.shape[1]

df.size

df.fillna(df.mean())

df[df['Age'].isnull()]

df.isnull().sum()

df.shape

df.drop(['Cabin'],axis=1,inplace=True)

df['Age'].fillna(df['Age'].mean(),inplace=True)

df['Embarked'].value_counts()

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()

"""### Data Formatting and Data Normalization

#### Summarize the types of variables by checking the data types (i.e., character, numeric, integer, factor, and logical) of the variables in the data set.
"""

df.dtypes

col_list=df.columns[df.dtypes=='object']
for i in col_list:
  print(i,df[i].value_counts(),sep='\n',end='\n')
  print('Nunique',df[i].nunique(),end='\n\n')

col_list=df.columns[df.dtypes!='object']
for i in col_list:
  print(i,df[i].value_counts(),sep='\n',end='\n')
  print('Nunique',df[i].nunique(),end='\n\n')

df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

"""#### If variables are not in the correct data type, apply proper type conversions. 

"""

df['Age']=df['Age'].astype('int32')

df['Survived']=df['Survived'].astype('int32')

df['Pclass']=df['Pclass'].astype('int32')

df['SibSp']=df['SibSp'].astype('int32')

df['Parch']=df['Parch'].astype('int32')

df['Fare']=df['Fare'].astype('Float32')

"""### Turn categorical variables into quantitative variables in Python.

Categorical To Numerical

head= to see colums and data
"""

df.head(10)

"""### 1. Using Replace() method"""

df['Sex'].replace(['male','female'],[0,1],inplace=True)

"""### 2. Using Map method

embarked= S,C,Q

see head
"""

enc_dict={'S':0,'C':1,'Q':2}

df['Embarked_enc']=df['Embarked'].map(enc_dict)

df.head(2)

"""Above methods are nominal and ordinal also"""

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()

enc=pd.DataFrame(ohe.fit_transform(df[['Embarked']]).toarray())

enc

df=df.join(enc)

df.head()

