# -*- coding: utf-8 -*-
"""F_GRPA9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gWuY6VaIzOjlMuVOq96Jen_Z0Aiu7u9a
"""

import pandas as pd
import numpy as np
import seaborn as sns

df= sns.load_dataset('titanic')

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

df['age'].fillna(df['age'].mean(),inplace=True)

df['embarked'].value_counts()

df['embarked'].fillna('S',inplace=True)

#embarked null values are removed successfully`
df.isnull().sum()

df.fillna(method='ffill',inplace=True)

df.isnull().sum()

#while implementing ffill one last record is not replaced so implement bfill once
df.fillna(method='bfill',inplace=True)

df.isnull().sum()

sns.boxplot(x='sex',y='age',hue='survived',data=df)
#mulit variate analysis

