# -*- coding: utf-8 -*-
"""F_GRPA10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAXkNpLgUokIcvkRshD8uI1JTHpQqCM7

Group A
Assignment N0. 10
Title Visualization
"""

import pandas as pd

import numpy as np

import seaborn as sns

df=sns.load_dataset('iris')

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

"""Q1. """

df.dtypes

"""q2. create a histogram for each dataset"""

sns.histplot(df['sepal_length'])
#EDA

"""Normal distributed
uniform dist
+ve dist
-ve dist
"""

#kde= kernal density estimation

sns.kdeplot(df['sepal_length'])

sns.distplot(df['sepal_length'])
#data in this columns are not normally distributed

df['sepal_length'].skew()

"""figure level & access level concept """

sns.histplot(df['sepal_length'])
//NORMAL DISTRIBUTION

sns.histplot(df['sepal_width'])
//NORMAL DISTRIBUTION

sns.histplot(df['petal_length'])
#NON NORMAL DISTRIBUTION

sns.histplot(df['petal_width'])
#NON NORMAL DISTRIBUTION

sns.histplot(df['species'])
#UNIFORM DISTRIBUTION

"""kde & distplot can be used only for numerical values"""

sns.boxplot(df['sepal_length'])

sns.boxplot(df['sepal_width'])
#we found outlier's  only in sepal width column

sns.boxplot(df['petal_length'])

sns.boxplot(df['petal_width'])

sns.kdeplot(df)
#KERNEL DENSITY ESTIMATION
#WE CAN ONLY PLOT

df.petal_length.skew()

df.petal_width.skew()

df.sepal_length.skew()

df.sepal_width.skew()

sns.boxplot(df)
#OUTLIER ONLY IN SEPAL WIDTH



sns.histplot(df)

