# -*- coding: utf-8 -*-
"""F_GRPA03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18RYLBOd-4p3ZqiHWewqJ9rqeWZ3oyyNM

#Group A
#Assignment No 3
"""

import pandas as pd
import numpy as np
import seaborn as sns

df= sns.load_dataset('tips')

df.head()

df.shape

df.info()

df.isnull().sum()

df.describe()

df['smoker'].value_counts()

df['tip'].value_counts()

df['smoker'].value_counts()

df.groupby('smoker').describe()

df.groupby('smoker')[['total_bill','tip']].describe()

df['time'].value_counts()

df.groupby('time')[['total_bill','tip']].describe()

df['sex'].value_counts()

df.groupby('sex')[['total_bill','tip']].describe()

df['day'].value_counts()

df.groupby('day')[['total_bill','tip']].describe()

df['size'].value_counts()

df.groupby('size')[['total_bill','tip']].describe()

df[df['day']=='Sun']['total_bill'].describe()

"""#Question 2"""

df1=sns.load_dataset('iris')

df1.head()

df1.shape

df1.info()

df1.isnull().sum()

df1.describe()

df1['species'].value_counts()

df1.groupby('species')['sepal_length'].describe()

df1.groupby('species')['sepal_width'].describe()

df1.groupby('species')['petal_length'].describe()

df1.groupby('species')['petal_width'].describe()

"""instead of using describe if we want single statistical information 
we can use min(),max(),mean(),meadian(),std(),count(),quantile(0.25)//quantile used for showing percentage
"""

